name: cron

on:
  schedule:
    - cron: '*/90 * * * *'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: run task
        run: |
          task
